# Generated by Django 4.2.13 on 2024-07-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cover',
            field=models.ImageField(blank=True, upload_to='products/product_cover/', verbose_name='Product Image'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='body',
            field=models.TextField(verbose_name='your comment: '),
        ),
        migrations.AlterField(
            model_name='comments',
            name='stars',
            field=models.CharField(choices=[('1', 'Very Bad'), ('2', 'Bad'), ('3', 'Normal'), ('4', 'Good'), ('5', 'Perfect')], max_length=10, verbose_name='rate'),
        ),
    ]
