# Generated by Django 4.2.13 on 2024-07-13 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_products_cover_alter_comments_body_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='cover',
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='product/product_cover/', verbose_name='Product Image'),
        ),
    ]
